var JOURNAL = [
  {"events":["carrot","exercise","weekend"],"migraine":false},
  {"events":["bread","pudding","brushed teeth","weekend","touched tree"],"migraine":false},
  {"events":["carrot","nachos","brushed teeth","cycling","weekend"],"migraine":false},
  {"events":["brussel sprouts","ice cream","brushed teeth","computer","weekend"],"migraine":false},
  {"events":["potatoes","candy","brushed teeth","exercise","weekend","dentist"],"migraine":false},
  {"events":["brussel sprouts","pudding","brushed teeth","running","weekend"],"migraine":false},
  {"events":["pizza","brushed teeth","computer","work","touched tree"],"migraine":false},
  {"events":["bread","beer","brushed teeth","cycling","work"],"migraine":false},
  {"events":["cauliflower","brushed teeth","work"],"migraine":false},
  {"events":["pizza","brushed teeth","cycling","work"],"migraine":false},
  {"events":["lasagna","nachos","brushed teeth","work"],"migraine":false},
  {"events":["brushed teeth","weekend","touched tree"],"migraine":false},
  {"events":["lettuce","brushed teeth","television","weekend"],"migraine":false},
  {"events":["spaghetti","brushed teeth","work"],"migraine":false},
  {"events":["brushed teeth","computer","work"],"migraine":false},
  {"events":["lettuce","nachos","brushed teeth","work"],"migraine":false},
  {"events":["carrot","brushed teeth","running","work"],"migraine":false},
  {"events":["brushed teeth","work"],"migraine":false},
  {"events":["cauliflower","reading","weekend"],"migraine":false},
  {"events":["bread","brushed teeth","weekend"],"migraine":false},
  {"events":["lasagna","brushed teeth","exercise","work"],"migraine":false},
  {"events":["spaghetti","brushed teeth","reading","work"],"migraine":false},
  {"events":["carrot","ice cream","brushed teeth","television","work"],"migraine":false},
  {"events":["spaghetti","nachos","work"],"migraine":false},
  {"events":["cauliflower","ice cream","brushed teeth","cycling","work"],"migraine":false},
  {"events":["spaghetti","peanuts","computer","weekend"],"migraine":true},
  {"events":["potatoes","ice cream","brushed teeth","computer","weekend"],"migraine":false},
  {"events":["potatoes","ice cream","brushed teeth","work"],"migraine":false},
  {"events":["peanuts","brushed teeth","running","work"],"migraine":false},
  {"events":["potatoes","exercise","work"],"migraine":false},
  {"events":["pizza","ice cream","computer","work"],"migraine":false},
  {"events":["lasagna","ice cream","work"],"migraine":false},
  {"events":["cauliflower","candy","reading","weekend"],"migraine":false},
  {"events":["lasagna","nachos","brushed teeth","running","weekend"],"migraine":false},
  {"events":["potatoes","brushed teeth","work"],"migraine":false},
  {"events":["carrot","work"],"migraine":false},
  {"events":["pizza","beer","work","dentist"],"migraine":false},
  {"events":["lasagna","pudding","cycling","work"],"migraine":false},
  {"events":["spaghetti","brushed teeth","reading","work"],"migraine":false},
  {"events":["spaghetti","pudding","television","weekend"],"migraine":false},
  {"events":["bread","brushed teeth","exercise","weekend"],"migraine":false},
  {"events":["lasagna","peanuts","work"],"migraine":true},
  {"events":["pizza","work"],"migraine":false},
  {"events":["potatoes","exercise","work"],"migraine":false},
  {"events":["brushed teeth","exercise","work"],"migraine":false},
  {"events":["spaghetti","brushed teeth","television","work"],"migraine":false},
  {"events":["pizza","cycling","weekend"],"migraine":false},
  {"events":["carrot","brushed teeth","weekend"],"migraine":false},
  {"events":["carrot","beer","brushed teeth","work"],"migraine":false},
  {"events":["pizza","peanuts","candy","work"],"migraine":true},
  {"events":["carrot","peanuts","brushed teeth","reading","work"],"migraine":false},
  {"events":["potatoes","peanuts","brushed teeth","work"],"migraine":false},
  {"events":["carrot","nachos","brushed teeth","exercise","work"],"migraine":false},
  {"events":["pizza","peanuts","brushed teeth","television","weekend"],"migraine":false},
  {"events":["lasagna","brushed teeth","cycling","weekend"],"migraine":false},
  {"events":["cauliflower","peanuts","brushed teeth","computer","work","touched tree"],"migraine":false},
  {"events":["lettuce","brushed teeth","television","work"],"migraine":false},
  {"events":["potatoes","brushed teeth","computer","work"],"migraine":false},
  {"events":["bread","candy","work"],"migraine":false},
  {"events":["potatoes","nachos","work"],"migraine":false},
  {"events":["carrot","pudding","brushed teeth","weekend"],"migraine":false},
  {"events":["carrot","brushed teeth","exercise","weekend","touched tree"],"migraine":false},
  {"events":["brussel sprouts","running","work"],"migraine":false},
  {"events":["brushed teeth","work"],"migraine":false},
  {"events":["lettuce","brushed teeth","running","work"],"migraine":false},
  {"events":["candy","brushed teeth","work"],"migraine":false},
  {"events":["brussel sprouts","brushed teeth","computer","work"],"migraine":false},
  {"events":["bread","brushed teeth","weekend"],"migraine":false},
  {"events":["cauliflower","brushed teeth","weekend"],"migraine":false},
  {"events":["spaghetti","candy","television","work","touched tree"],"migraine":false},
  {"events":["carrot","pudding","brushed teeth","work"],"migraine":false},
  {"events":["lettuce","brushed teeth","work"],"migraine":false},
  {"events":["carrot","ice cream","brushed teeth","cycling","work"],"migraine":false},
  {"events":["pizza","brushed teeth","work"],"migraine":false},
  {"events":["spaghetti","peanuts","exercise","weekend"],"migraine":true},
  {"events":["bread","beer","computer","weekend","touched tree"],"migraine":false},
  {"events":["brushed teeth","running","work"],"migraine":false},
  {"events":["lettuce","peanuts","brushed teeth","work","touched tree"],"migraine":false},
  {"events":["lasagna","brushed teeth","television","work"],"migraine":false},
  {"events":["cauliflower","brushed teeth","running","work"],"migraine":false},
  {"events":["carrot","brushed teeth","running","work"],"migraine":false},
  {"events":["carrot","reading","weekend"],"migraine":false},
  {"events":["carrot","peanuts","reading","weekend"],"migraine":true},
  {"events":["potatoes","brushed teeth","running","work"],"migraine":false},
  {"events":["lasagna","ice cream","work","touched tree"],"migraine":false},
  {"events":["cauliflower","peanuts","brushed teeth","cycling","work"],"migraine":false},
  {"events":["pizza","brushed teeth","running","work"],"migraine":false},
  {"events":["lettuce","brushed teeth","work"],"migraine":false},
  {"events":["bread","brushed teeth","television","weekend"],"migraine":false},
  {"events":["cauliflower","peanuts","brushed teeth","weekend"],"migraine":false}
];

// This makes sure the data is exported in node.js —
// `require('./path/to/04_data.js')` will get you the array.
if (typeof module != "undefined" && module.exports)
  module.exports = JOURNAL;
